#!/bin/bash

# Source common functions
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/common.sh"

# Initialize script (parse args, validate env vars, set subscription)
init_script "$@"

# Get BASE_DIR relative to infra-foundation root
BASE_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"

echo "=== Setting up GitHub Actions Access ==="
log_dry_run
log_info "Script directory: $SCRIPT_DIR"
log_info "Repository base: $BASE_DIR"
log_info "Subscription: $SUBSCRIPTION_ID"
log_info "Tenant: $TENANT_ID"
echo ""

# Initialize service-principals.env file (clear if exists, we'll recreate it)
SP_IDS_FILE="${SCRIPT_DIR}/service-principals.env"

# Add header comment to the file (only in non-dry-run mode)
if [ "$DRY_RUN" != true ]; then
  cat > "$SP_IDS_FILE" <<EOF
# Service Principal IDs for GitHub Actions
# Generated by setup-access.sh - DO NOT EDIT MANUALLY
# Format: KEY=value (standard .env format)

EOF
else
  # In dry-run mode, just clear the file reference
  clear_file "$SP_IDS_FILE"
fi

# ============================================================================
# Step 5.1: Create Service Principals
# ============================================================================
echo "=== Step 5.1: Creating Service Principals ==="
echo ""

for ENV in dev test stage prod; do
  SP_NAME="sp-gha-${PROJECT}-infra-${ENV}"
  ENV_UPPER=$(echo "$ENV" | tr '[:lower:]' '[:upper:]')
  APP_ID_VAR="${ENV_UPPER}_SP_APP_ID"
  OBJECT_ID_VAR="${ENV_UPPER}_SP_OBJECT_ID"
  
  log_info "--- Creating Service Principal: ${SP_NAME} ---"
  
  # Create Service Principal
  if [ "$DRY_RUN" = true ]; then
    echo "[DRY-RUN] az ad sp create-for-rbac --name \"$SP_NAME\" --role \"Contributor\" --scopes \"/subscriptions/${SUBSCRIPTION_ID}\" --output json" >&2
    APP_ID="<app-id-would-be-generated-${ENV}>"
    OBJECT_ID="<object-id-would-be-retrieved-${ENV}>"
    log_success "App ID (Client ID): $APP_ID"
    log_success "Object ID: $OBJECT_ID"
  else
    SP_OUTPUT=$(az ad sp create-for-rbac \
      --name "$SP_NAME" \
      --role "Contributor" \
      --scopes "/subscriptions/${SUBSCRIPTION_ID}" \
      --output json)
    
    APP_ID=$(echo "$SP_OUTPUT" | jq -r '.appId')
    OBJECT_ID=$(az ad sp show --id "$APP_ID" --query id --output tsv)
    
    log_success "App ID (Client ID): $APP_ID"
    log_success "Object ID: $OBJECT_ID"
  fi
  
  # Store for later use (both in file and as environment variable)
  # Write in .env format (KEY=value, not export KEY=value)
  write_file "$SP_IDS_FILE" "${APP_ID_VAR}=$APP_ID"
  write_file "$SP_IDS_FILE" "${OBJECT_ID_VAR}=$OBJECT_ID"
  
  # Set environment variables directly (needed for dry-run mode)
  eval "export ${APP_ID_VAR}=\"$APP_ID\""
  eval "export ${OBJECT_ID_VAR}=\"$OBJECT_ID\""
  
  echo ""
done

# Load the file to load variables (only needed in non-dry-run mode for consistency)
if [ "$DRY_RUN" != true ]; then
  load_env_file "$SP_IDS_FILE"
fi

log_success "Service Principals created and IDs saved to ${SP_IDS_FILE}"
echo ""

# ============================================================================
# Step 5.2: Create Federated Identity Credentials
# ============================================================================
echo "=== Step 5.2: Creating Federated Identity Credentials ==="
echo ""

# Set GitHub organization and repository names
FOUNDATION_REPO="${ORGANIZATION}/infra-foundation"
PLATFORM_REPO="${ORGANIZATION}/infra-platform"
WORKLOAD_IDENTITY_REPO="${ORGANIZATION}/infra-workload-identity"

# For each environment
for ENV in dev test stage prod; do
  SP_NAME="sp-gha-${PROJECT}-infra-${ENV}"
  ENV_UPPER=$(echo "$ENV" | tr '[:lower:]' '[:upper:]')
  APP_ID_VAR="${ENV_UPPER}_SP_APP_ID"
  eval "APP_ID=\$$APP_ID_VAR"
  
  # Verify APP_ID is set
  if [ -z "$APP_ID" ]; then
    log_error "${APP_ID_VAR} is not set. Please check service-principals.env file."
    continue
  fi
  
  log_info "--- Creating FIC for ${SP_NAME} (App ID: ${APP_ID}) ---"
  
  # Get Object ID (skip in dry-run mode)
  if [ "$DRY_RUN" = true ]; then
    OBJECT_ID="<object-id-would-be-retrieved>"
  else
    OBJECT_ID=$(az ad sp show --id "$APP_ID" --query id --output tsv)
    
    if [ -z "$OBJECT_ID" ]; then
      log_error "Could not retrieve Object ID for Service Principal ${SP_NAME}"
      continue
    fi
  fi
  
  # FIC for infra-foundation repository (GitHub Environment)
  log_info "Creating FIC for infra-foundation (environment: ${ENV})..."
  run_cmd az ad app federated-credential create \
    --id "$APP_ID" \
    --parameters "{
      \"name\": \"GitHubInfraFoundationEnv-${ENV}\",
      \"issuer\": \"https://token.actions.githubusercontent.com\",
      \"subject\": \"repo:${FOUNDATION_REPO}:environment:${ENV}\",
      \"description\": \"GitHub Actions OIDC for infra-foundation repo ${ENV} environment\",
      \"audiences\": [\"api://AzureADTokenExchange\"]
    }" 2>/dev/null || log_warning "FIC may already exist, continuing..."
  
  # FIC for infra-platform repository (GitHub Environment)
  log_info "Creating FIC for infra-platform (environment: ${ENV})..."
  run_cmd az ad app federated-credential create \
    --id "$APP_ID" \
    --parameters "{
      \"name\": \"GitHubInfraPlatformEnv-${ENV}\",
      \"issuer\": \"https://token.actions.githubusercontent.com\",
      \"subject\": \"repo:${PLATFORM_REPO}:environment:${ENV}\",
      \"description\": \"GitHub Actions OIDC for infra-platform repo ${ENV} environment\",
      \"audiences\": [\"api://AzureADTokenExchange\"]
    }" 2>/dev/null || log_warning "FIC may already exist, continuing..."
  
  # FIC for infra-workload-identity repository (GitHub Environment)
  log_info "Creating FIC for infra-workload-identity (environment: ${ENV})..."
  run_cmd az ad app federated-credential create \
    --id "$APP_ID" \
    --parameters "{
      \"name\": \"GitHubInfraWorkloadIdentityEnv-${ENV}\",
      \"issuer\": \"https://token.actions.githubusercontent.com\",
      \"subject\": \"repo:${WORKLOAD_IDENTITY_REPO}:environment:${ENV}\",
      \"description\": \"GitHub Actions OIDC for infra-workload-identity repo ${ENV} environment\",
      \"audiences\": [\"api://AzureADTokenExchange\"]
    }" 2>/dev/null || log_warning "FIC may already exist, continuing..."
  
  log_success "FIC created for ${SP_NAME}"
  echo ""
done

log_success "Federated Identity Credentials created"
echo ""

# ============================================================================
# Step 5.3: Assign Additional RBAC Roles
# ============================================================================
echo "=== Step 5.3: Assigning Additional RBAC Roles ==="
echo ""

for ENV in dev test stage prod; do
  SP_NAME="sp-gha-${PROJECT}-infra-${ENV}"
  ENV_UPPER=$(echo "$ENV" | tr '[:lower:]' '[:upper:]')
  APP_ID_VAR="${ENV_UPPER}_SP_APP_ID"
  eval "APP_ID=\$$APP_ID_VAR"
  
  # Verify APP_ID is set
  if [ -z "$APP_ID" ]; then
    log_error "${APP_ID_VAR} is not set. Please check service-principals.env file."
    continue
  fi
  
  RG_NAME="rg-${PROJECT}-${ENV}"
  SA_NAME="tfstate${ORGANIZATION_FOR_SA}${PROJECT}${ENV}"
  
  log_info "--- Assigning roles for ${SP_NAME} (App ID: ${APP_ID}) ---"
  
  # Contributor role on Resource Group (already assigned, but verify)
  log_info "Assigning Contributor role on Resource Group..."
  run_cmd az role assignment create \
    --assignee "$APP_ID" \
    --role "Contributor" \
    --scope "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}" \
    --output none 2>/dev/null || log_warning "Role may already exist"
  
  # User Access Administrator (to assign roles to Managed Identities later)
  log_info "Assigning User Access Administrator role on Resource Group..."
  run_cmd az role assignment create \
    --assignee "$APP_ID" \
    --role "User Access Administrator" \
    --scope "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}" \
    --output none 2>/dev/null || log_warning "Role may already exist"
  
  # Storage Blob Data Contributor on State Storage Account
  log_info "Assigning Storage Blob Data Contributor role on Storage Account..."
  run_cmd az role assignment create \
    --assignee "$APP_ID" \
    --role "Storage Blob Data Contributor" \
    --scope "/subscriptions/${SUBSCRIPTION_ID}/resourceGroups/${RG_NAME}/providers/Microsoft.Storage/storageAccounts/${SA_NAME}" \
    --output none 2>/dev/null || log_warning "Role may already exist"
  
  log_success "Roles assigned for ${SP_NAME}"
  echo ""
done

echo "=== Setup Complete ==="
log_dry_run_complete
echo ""
echo "Summary:"
echo "  - Service Principals created: 4 (one per environment)"
echo "  - Federated Identity Credentials created: 12 (3 repos × 4 environments)"
echo "  - RBAC roles assigned: Contributor, User Access Administrator, Storage Blob Data Contributor"
echo ""
if [ "$DRY_RUN" != true ]; then
  echo "Service Principal IDs saved to: ${SP_IDS_FILE}"
  echo ""
  echo "Next steps:"
  echo "  1. Verify service-principals.env file contains all Service Principal IDs"
  echo "  2. Add service-principals.env to .gitignore (if not already added)"
  echo "  3. Configure GitHub Secrets (see Step 9.3 in playbook)"
else
  echo "Service Principal IDs would be saved to: ${SP_IDS_FILE}"
fi

